controller_names:
  - joint_trajectory_controller
  - gripper_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

gripper_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - gripper_jaw1_joint
